name = "trivagofuckyourselves"
main = "webapp/dist/worker.js"
compatibility_date = "2024-12-18"
account_id = ""
workers_dev = true

[env.production]
route = { pattern = "trivagofuckyourselves.example.com/*", zone_name = "example.com" }

[env.staging]
workers_dev = true

[[kv_namespaces]]
binding = "WEBHOOK_DATA"
id = ""
preview_id = ""

[vars]
ENVIRONMENT = "development"

[triggers]
crons = []